### ISSUE TITLE
Every Project Need a README

### ISSUE THREAD

**Issue by simonprovost** [lapprenti18/my_spotify#1]
Hey **mate**,

Here you have a great project but we don't know how to run it, how contribute to it or even zero screenshot of the beautiful app you have made.

Here you can see few great readme to take as example: https://github.com/matiassingers/awesome-readme

The readme is your first page, the first impression of other developers when they coming on your repository. 📣
**Simon**.

**Comment by EmeryckClerin** [comment]
Hey mate,

Sorry, I had forgotten that, now I have one.

Thank you.
